version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    target-branch: core
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    target-branch: core
    schedule:
      interval: weekly
